/*calculate the number of orders per month in 2018*/
select date_format(order_purchase_timestamp,'%Y-%m') as order_month,
count(order_id) as total_orders
from orders
where year(order_purchase_timestamp)=2018
group by order_month
order by order_month;

/*Find the average number of products per order, grouped by customer city*/
select * from customers;
select c.customer_city, round(avg(t.items_per_order),2) as avg_products_per_order
from (select oi.order_id, count(*) as items_per_order
from order_items oi
group by oi.order_id) as t
join orders o on o.order_id = t.order_id
join customers c on c.customer_id = o.customer_id 
group by c.customer_city
order by avg_products_per_order desc;

/*Calculate the percentage of total revenue contributed by each product category*/
select p.`product category`,
round(sum(oi.price+oi.freight_value),2) as total_sales,
round(sum(oi.price+freight_value)*100/(select sum(price+freight_value) from order_items),2) as percent_contribution
from order_items oi
join products p on oi.product_id = p.product_id
join (select sum(price + freight_value)as total_sales1
from order_items) as grand_total_sales
group by p.`product category`
order by percent_contribution desc;

/*Identify correlation between product price and number of times a product has been purchased*/
select * from order_items;
select p.product_id,
round(avg(oi.price),2) as avg_price,
count(oi.order_id) as count_of_purchase
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_id
order by count_of_purchase;

/*calculate the total revenue generated by each sellers, and rank them by revenue*/
select * from sellers;
select s.seller_id,
round(sum(oi.price+oi.freight_value),2) as total_revenue,
rank() over(order by round(sum(oi.price+oi.freight_value),2)desc) as ranking
from sellers s
join order_items oi on s.seller_id = oi.seller_id
group by s.seller_id
order by total_revenue desc;